// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Aside: typeof import('./src/components/layout/aside/Aside.vue')['default']
    Avatar: typeof import('./src/components/layout/header/components/Avatar.vue')['default']
    ChangeLanguage: typeof import('./src/components/changeLanguage/ChangeLanguage.vue')['default']
    Content: typeof import('./src/components/layout/content/Content.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Header: typeof import('./src/components/layout/header/Header.vue')['default']
    Icon: typeof import('./src/components/icon/Icon.vue')['default']
    Info: typeof import('./src/components/layout/header/components/Info.vue')['default']
    Layout: typeof import('./src/components/layout/index.vue')['default']
    NavigationBar: typeof import('./src/components/layout/header/components/NavigationBar.vue')['default']
    Screenfull: typeof import('./src/components/layout/header/components/Screenfull.vue')['default']
  }
}

export { }
